services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - microservices-network

  dbmysql:
    image: mysql:latest
    container_name: dbmysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=superSecretPassword
    volumes:
      - mysqldata:/var/lib/mysql
    networks:
      - microservices-network
    restart: always

  # Microservices
  user-management:
    build:
      context: ./userManagement
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    env_file:
      - ./userManagement/.env
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    restart: unless-stopped

  customer-management:
    build:
      context: ./customerManagement
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    env_file:
      - ./customerManagement/.env
    ports:
      - "3001:3001"
    networks:
      - microservices-network
    restart: unless-stopped

  sale-management:
    build:
      context: ./saleManagement
      dockerfile: Dockerfile
    depends_on:
      - dbmysql
    env_file:
      - ./saleManagement/.env
    ports:
      - "3002:3002"
    networks:
      - microservices-network
    restart: unless-stopped

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    depends_on:
      - user-management
      - customer-management
      - sale-management
    env_file:
      - ./gateway/.env
    ports:
      - "2999:2999"
    networks:
      - microservices-network
    restart: unless-stopped

networks:
  microservices-network:
    driver: bridge

volumes:
  mongodb_data:
  mysqldata: